name: static-analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install latest framework deps
        run: |
          composer require --dev laravel/laravel
          composer require --dev slim/slim

      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: 'highest'

      - name: Static Code Analysis
        run: composer analyse
