name: static-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: 'highest'

      - name: Install frameworks
        run: |
          composer require laravel/laravel
          composer require  slim/slim

      - name: Static Code Analysis
        run: composer analyse
